accounts/urls.py
"""Define patrones URL para accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Incluye url de autenticación predeterminadas.
    path ('', include('django.contrib.auth.urls')),
    # Página de registro.
    path('register/', views.register, name='register'),
]

learning_logs/urls.py
"""Define patrones de URL para learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Página de inicio
    path('', views.index, name = 'index'),
    #Página que muestra todos los temas
    path('topics', views.topics, name = 'topics'),
    # Página de detalles para un tema individual
    path('topics/<int:topic_id>/', views.topic, name = 'topic'),
    # Página para añadir un tema nuevo
    path('new_topic/', views.new_topic, name = 'new_topic'),
    # Página para añadir una nueva entrada
    path('new_entry/<int:topic_id>/', views.new_entry, name = 'new_entry'),
    # Página para editar una entrada
    path('edit_entry/<int:entry_id>/', views.edit_entry, name = 'edit_entry'),
]

ll_project/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Crea nuestros modelos aquí.
class Topic (models.Model):
    """Un tema sobre el que está aprendiendo el usuario."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Deviuelve una representación del modelo como cadena."""
        return self.text
    
class Entry(models.Model):
    """Algo específico aprendido sobre un tema."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Devuelve una cadena simple que representa la entrada."""
        if len(self.text) < 50:
            return self.text
        else:
            return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs = {'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Registra un nuevo usuario."""
    if request.method != 'POST':
        # Muestra un formulario de registro en blanco.
        form = UserCreationForm()
    else:
        # Procesa un formulario cumplimentado.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Inicia la sesión y envía al inicio.
            login(request, new_user)
            return redirect('learning_logs:index')
        
    # Muestra un formulario en blanco o inválido.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index (request):
    """La página de inicio para learning_logs."""
    return render(request, 'learning_logs/index.html')

@login_required
def topics (request):
    """Muestra todos los temas."""
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic (request, topic_id):
    """Muestra un tema concreto y todas sus entradas."""
    topic = Topic.objects.get(id = topic_id)
    # Se asegura de que el tema pertenece al usuario actual.
    check_topic_owner(request, topic.id)
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic (request):
    """Añade un tema nuevo."""
    if request.method != 'POST':
        # No se ha enviado datos; se crea un formulario en blanco.
        form = TopicForm()
    else:
        # Datos POST enviados; procesa datos.
        form = TopicForm(data = request.POST)
        if form.is_valid():
            new_topic = form.save(commit = False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
        
    # Muestra un formulario en blanco o inválido.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry (request, topic_id):
    """Añade una entrada nueva para un tema en particular."""
    topic = Topic.objects.get(id = topic_id)
    # Se asegura de que el tema pertenece al usuario actual.
    check_topic_owner(request, topic.id)

    if request.method != 'POST':
        # No se ha enviado datos; se crea un formulario en blanco.
        form = EntryForm()
    else:
        # Datos POST enviados; procesa los datos.
        form = EntryForm(data = request.POST)
        if form.is_valid():
            new_entry = form.save(commit = False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id = topic_id)
        
    # Muestra un formulario en blanco o inválido.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry (request, entry_id):
    """Edita una entrada existente."""
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    # Se asegura de que el tema pertenece al usuario actual.
    check_topic_owner(request, topic.id)

    if request.method != 'POST':
        # Solicitud inicial; prerrellena el formulario con la entrada actual.
        form = EntryForm(instance = entry)
    else:
        # Datos post enviados; procesar datos.
        form = EntryForm(instance = entry, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic.id)
        
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

def check_topic_owner (request, topic_id):
    """Comprueba que el tema pertenece al usuario actual."""
    topic = Topic.objects.get(id = topic_id)
    if topic.owner != request.user:
        raise Http404
    return topic

learning_logs/templates/learning_logs/base.html
<!doctype html>
<html lang = 'eng'>
<head>
    <meta charset="utf-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                Learning Log</a>

            <button class="navbar-toggler" type="button" 
                data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" 
                        href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul><!-- Fin de los enlaces a la izquierda de la barra de navegación -->

                <!-- Enlaces vinculados a cuentas -->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="nav-link">Hello, {{ user.username }}.
                        </span></li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">
                            Register</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">
                            Log in</a></li>
                    {% endif %}
                </ul><!-- Fin de los enlaces vinculados a cuentas -->

                {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" 
                        class="btn btn-outline-secondary btn-sm">
                        Log out</button>
                </form>
                {% endif %}

        </div><!-- Cierra los elementos plegables de la barra de navegación -->
    </nav><!-- Fin de la barra de navegación -->

    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>{{ topic }}.</h2>
{% endblock page_header %}

{% block content %}
    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Edit entry" %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Track your learning.</h1>

            <p class="lead">Make your own Learning Log, and keep a list of the 
                topics you´re learning about. Whenever you learn something new
                about a topic, make an entry summarizing what you´ve learned.
            </p>

            <a class="btn btn-primary btn-lg mt-1"
                href="{% url 'accounts:register' %}">Register &raquo;</a>
        </div>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>{{ topic }}.</h2>
{% endblock page_header %}


{% block content %}
    <p> Add a new entry</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Add entry" %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>New topic.</h2>
{% endblock page_header %}

{% block content %}
  <p>Add a new topic:</p>

  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add topic" %}
  </form>
{% endblock content %}
```

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}

    <h1>{{ topic.text }}</h1>

{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">
            Add a new entry</a>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <!-- Card header with timestamp and edit link -->
            <h4 class = "card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        Edit entry</a></small>
            </h4>
            <!-- Card body with entry text -->
            <div class="card-body">
                <p class="card-text">{{ entry.text|linebreaks }}</p></div>
        </div>
    {% empty %}
        <li>No entries have been added yet.</li>
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}

    <h2> Topics </h2>

{% endblock page_header %}

{% block content %}

    <ul class="list-group border-bottom pb-2 mb-4">
        {% for topic in topics %}
        <div class="card mb-3">
            <!-- Card header with timestamp and edit link -->
            <h7 class = "card-header">
                <a href="{% url 'learning_logs:topic' topic.id %}"> 
                    {{ topic.text }}</a>
            </h7>
        </div>
        {% empty %}
            <li class="list-group-item border-0"> No topics have been added yet.
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'learning_logs:new_topic' %}"> Add a new topic </a>

{% endblock content %}